previewsEnabled: true
previewsExpireAfterDays: 3
services:
- type: web
  plan: starter plus
  previewPlan: starter
  name: express-backend
  env: node
  buildCommand: cd backend && yarn
  startCommand: cd backend && yarn start
- type: web
  name: render-todo
  env: static
  buildCommand: cd frontend && yarn install && yarn build
  staticPublishPath: ./frontend/build
databases:
- name: postgres_db
  databaseName: test_db
  user: test_user
  plan: standard
  previewPlan: starter
